// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnApu6dqqzi8mPagv--PKqnCfOtcxR84w',
    appId: '1:1008900223267:web:0a6cf5a1737b858988dc96',
    messagingSenderId: '1008900223267',
    projectId: 'auth-807c9',
    authDomain: 'auth-807c9.firebaseapp.com',
    storageBucket: 'auth-807c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmcN6wIWY7q0eEvFl5V07KSFXwtJL4niE',
    appId: '1:1008900223267:android:fa8be1f6b587fc9a88dc96',
    messagingSenderId: '1008900223267',
    projectId: 'auth-807c9',
    storageBucket: 'auth-807c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvQ69ce7LxO0Y37ceZ0lbJaT0PO8jgcIg',
    appId: '1:1008900223267:ios:bf6bfe85e3f5f17e88dc96',
    messagingSenderId: '1008900223267',
    projectId: 'auth-807c9',
    storageBucket: 'auth-807c9.appspot.com',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvQ69ce7LxO0Y37ceZ0lbJaT0PO8jgcIg',
    appId: '1:1008900223267:ios:bf6bfe85e3f5f17e88dc96',
    messagingSenderId: '1008900223267',
    projectId: 'auth-807c9',
    storageBucket: 'auth-807c9.appspot.com',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnApu6dqqzi8mPagv--PKqnCfOtcxR84w',
    appId: '1:1008900223267:web:19f0e861ae70f00688dc96',
    messagingSenderId: '1008900223267',
    projectId: 'auth-807c9',
    authDomain: 'auth-807c9.firebaseapp.com',
    storageBucket: 'auth-807c9.appspot.com',
  );

}